# Generated by Django 3.0.5 on 2020-04-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_lastname', models.CharField(max_length=30)),
                ('member_firstname', models.CharField(max_length=30)),
                ('member_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_num', models.CharField(max_length=30)),
                ('resort_name', models.CharField(max_length=30)),
            ],
        ),
    ]
