# Generated by Django 3.0.5 on 2020-04-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resort',
            new_name='Resorts',
        ),
    ]
