# Generated by Django 3.0.5 on 2020-04-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointsApp', '0002_auto_20200410_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='resorts',
            name='resort_aff_pdr_ind',
            field=models.CharField(default='D', max_length=1),
        ),
    ]
