# Generated by Django 3.0.5 on 2020-04-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointsApp', '0003_resorts_resort_aff_pdr_ind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resorts',
            name='resort_aff_pdr_ind',
            field=models.CharField(choices=[('D', 'Domestic'), ('P', 'PDR'), ('A', 'Affiliate')], default='D', max_length=1),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resv_begin_date', models.DateField()),
                ('resv_end_date', models.DateField()),
                ('elig_rev', models.DecimalField(decimal_places=2, max_digits=11)),
                ('base_points', models.IntegerField()),
                ('bonus_points', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointsApp.Members')),
                ('resort_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointsApp.Resorts')),
            ],
        ),
    ]
